export const memberSelect = {
  id: true,
  firstName: true,
  lastName: true,
  email: true,
  password: false,
  codiceFiscale: true,
  birthDate: true,
  birthComune: true,
  birthCountry: true,
  phoneNumber: true,
  address: true,
  membershipCardNumber: true,
  memberSince: true,
  isAdmin: true,
  createdAt: true,
  updatedAt: true,
} as const;
