-- AlterTable
ALTER TABLE "Purchase" ADD COLUMN     "total" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "PurchasedItem" ADD COLUMN     "total" DOUBLE PRECISION NOT NULL DEFAULT 0;
